name: Feature request
description: Create a feature request to help us improve
title: '[Feature]: '
labels: ['enhancement']
body:
    - type: textarea
      id: description
      attributes:
          label: Describe the feature request
          description: A clear and concise description of what the feature request is.
      validations:
          required: true
    - type: textarea
      id: considerations_potential_problems
      attributes:
          label: Considerations and potential problems
          description: Write your considerations and potential problems you may think can be encountered.
      validations:
          required: true
    - type: textarea
      id: context
      attributes:
          label: Additional context
          description: Add any other context about the feature here.
      validations:
          required: false