name: Centauri CI (Lint & Test)

on: [ push, pull_request ]

permissions:
    contents: read

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.20.5
            - name: Lint
              uses: golangci/golangci-lint-action@v3
              with:
                  version: latest
    test:
        name: Test
        needs: lint
        runs-on: ubuntu-latest
        env:
            CENTAURI_BOT_ID: ${{ secrets.CENTAURI_BOT_ID }}
            CENTAURI_BOT_TOKEN: ${{ secrets.CENTAURI_BOT_TOKEN }}
            CENTAURI_CHANNEL_ID: ${{ secrets.CENTAURI_CHANNEL_ID }}
            CENTAURI_GUILD_ID: ${{ secrets.CENTAURI_GUILD_ID }}
            CENTAURI_USER_ID: ${{ secrets.CENTAURI_USER_ID }}
        steps:
            - uses: actions/checkout@v3
            - name: Set up Go
              uses: actions/setup-go@v3
              with:
                  go-version: 1.20.5
            - name: Build
              run: go build -v ./...
            - name: Test
              run: go test -v ./...
