name: Centauri CD (Deploy Documentation)

on:
    release:
        types: [ published ]
    workflow_dispatch:

permissions:
    contents: read

jobs:
    deploy-documentation:
        name: Deploy Documentation
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: redkubes/docusaurus-deploy-action@v1.2
              with:
                  source-folder: documentation
                  git-user: kkrypt0nn
                  git-password: ${{ secrets.PAT }}
                  deployment-branch: gh-pages
